import { Bot, Database, FileSearch, Lock, ShieldCheck, TriangleAlert } from 'lucide-react'

const Section = ({ Icon, title, children }) => (
  <section className="card card-pad">
    <div className="row" style={{ marginBottom: '.6rem' }}><Icon size={18} style={{ color: 'var(--brand-600)' }} /><h2>{title}</h2></div>
    <div className="stack small" style={{ color: 'var(--text)' }}>{children}</div>
  </section>
)

export default function About() {
  return (
    <div className="content fade-in" style={{ maxWidth: 900 }}>
      <div className="page-head"><div><h1>About Nia and this portal</h1><p>A college project (AI Application, PGDM Business Data Analytics).</p></div></div>
      <div className="stack">
        <div className="alert warn"><TriangleAlert size={16} /><div><b>Fictional company, fictional documents, demo employee data.</b> Nexora Technologies Limited does not exist. Nia is an AI assistant and does not give HR or legal advice. Statutory figures in the documents have not been verified against the Acts.</div></div>
        <Section Icon={FileSearch} title="How Nia answers">
          <p>Nia searches 9 Nexora HR policy PDFs (134 pages, 386 searchable sections). Each question runs a keyword search (BM25) and a meaning-based search (BAAI/bge-small-en-v1.5 embeddings), merges them, and re-ranks the best matches with a small cross-encoder. If an amendment circular changes a clause, the circular is always included.</p>
          <p>The language model writes an answer only from those sections and must cite each one. The server then checks every citation: invented sources are removed, the quoted text must be found on the cited PDF page, and any sentence with a number that is not in its source is dropped. If nothing reliable remains, Nia says the documents don't cover it and offers an HR ticket.</p>
          <p>Sensitive topics (harassment, discrimination, distress, legal or pay disputes) always go to a human channel; Nia explains the process but does not give advice or judge a situation.</p>
        </Section>
        <Section Icon={Bot} title="Models used">
          <p><b>Main model:</b> gpt-oss:120b through Ollama's cloud API. <b>Fallback:</b> Google Gemini / Gemma models on the free tier, used automatically if the main model is busy or down. <b>Search models</b> run on the server itself (no external call).</p>
          <p>Free tiers have usage limits. If they are reached you will see "The free model limit was reached, please try again shortly." Repeated questions are answered from a cache.</p>
        </Section>
        <Section Icon={Lock} title="Privacy notice">
          <p><b>Your questions are sent to a third-party AI provider</b> (Ollama, or Google if the fallback is used) together with the relevant policy text, so that an answer can be written. Do not type personal, health or confidential information. Free-tier providers may use submitted data to improve their services.</p>
          <p>This server does <b>not store the text of your messages</b>. It keeps anonymised statistics (route, topic, response time, token counts and a one-way hash of the question) for the HR Insights page. Your chat history and profile (grade, location) are kept only in your own browser; "New chat" clears the conversation.</p>
          <p>Leave balances and tickets belong to fictional demo employees. Nia only ever shows the signed-in demo employee's own data.</p>
        </Section>
        <Section Icon={ShieldCheck} title="Guardrails">
          <p>Prompt-injection screening (including other languages and encoded text), no access to other employees' data, 800-character messages, 20 questions per chat, per-network rate limits, and answers limited to the policy documents.</p>
        </Section>
        <Section Icon={Database} title="Data">
          <p>Documents, circulars and 300 demo employees were generated by code for this project. Source and evaluation results are in the project repository.</p>
        </Section>
      </div>
    </div>
  )
}
